project:
  type: website
  output-dir: docs

website:
  title: "Mi primera chamba"
  image: icon.png
  navbar:
    logo: icon.png
    title: false
    left:
      - href: index.qmd
        text: Hola
      - about.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true
    toc-location: right
    toc-title: Contenidos



